// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyActionArgs {
    pub action_json: String,
}

impl From<ApplyActionArgs> for super::Reducer {
    fn from(args: ApplyActionArgs) -> Self {
        Self::ApplyAction {
            action_json: args.action_json,
        }
    }
}

impl __sdk::InModule for ApplyActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_action {
    /// Request that the remote module invoke the reducer `apply_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_action:apply_action_then`] to run a callback after the reducer completes.
    fn apply_action(&self, action_json: String) -> __sdk::Result<()> {
        self.apply_action_then(action_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_action_then(
        &self,
        action_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_action for super::RemoteReducers {
    fn apply_action_then(
        &self,
        action_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ApplyActionArgs { action_json }, callback)
    }
}
