// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::avatar_pose_type::AvatarPose;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `avatar_pose`.
///
/// Obtain a handle from the [`AvatarPoseTableAccess::avatar_pose`] method on [`super::RemoteTables`],
/// like `ctx.db.avatar_pose()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.avatar_pose().on_insert(...)`.
pub struct AvatarPoseTableHandle<'ctx> {
    imp: __sdk::TableHandle<AvatarPose>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `avatar_pose`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AvatarPoseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AvatarPoseTableHandle`], which mediates access to the table `avatar_pose`.
    fn avatar_pose(&self) -> AvatarPoseTableHandle<'_>;
}

impl AvatarPoseTableAccess for super::RemoteTables {
    fn avatar_pose(&self) -> AvatarPoseTableHandle<'_> {
        AvatarPoseTableHandle {
            imp: self.imp.get_table::<AvatarPose>("avatar_pose"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AvatarPoseInsertCallbackId(__sdk::CallbackId);
pub struct AvatarPoseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AvatarPoseTableHandle<'ctx> {
    type Row = AvatarPose;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AvatarPose> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AvatarPoseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarPoseInsertCallbackId {
        AvatarPoseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AvatarPoseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AvatarPoseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AvatarPoseDeleteCallbackId {
        AvatarPoseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AvatarPoseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AvatarPoseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AvatarPoseTableHandle<'ctx> {
    type UpdateCallbackId = AvatarPoseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AvatarPoseUpdateCallbackId {
        AvatarPoseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AvatarPoseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `owner_key` unique index on the table `avatar_pose`,
/// which allows point queries on the field of the same name
/// via the [`AvatarPoseOwnerKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.avatar_pose().owner_key().find(...)`.
pub struct AvatarPoseOwnerKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AvatarPose, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AvatarPoseTableHandle<'ctx> {
    /// Get a handle on the `owner_key` unique index on the table `avatar_pose`.
    pub fn owner_key(&self) -> AvatarPoseOwnerKeyUnique<'ctx> {
        AvatarPoseOwnerKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("owner_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AvatarPoseOwnerKeyUnique<'ctx> {
    /// Find the subscribed row whose `owner_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AvatarPose> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AvatarPose>("avatar_pose");
    _table.add_unique_constraint::<String>("owner_key", |row| &row.owner_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AvatarPose>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AvatarPose>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AvatarPose`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait avatar_poseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AvatarPose`.
    fn avatar_pose(&self) -> __sdk::__query_builder::Table<AvatarPose>;
}

impl avatar_poseQueryTableAccess for __sdk::QueryTableAccessor {
    fn avatar_pose(&self) -> __sdk::__query_builder::Table<AvatarPose> {
        __sdk::__query_builder::Table::new("avatar_pose")
    }
}
