// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AvatarPose {
    pub owner: __sdk::Identity,
    pub x: f32,
    pub y: f32,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for AvatarPose {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AvatarPose`.
///
/// Provides typed access to columns for query building.
pub struct AvatarPoseCols {
    pub owner: __sdk::__query_builder::Col<AvatarPose, __sdk::Identity>,
    pub x: __sdk::__query_builder::Col<AvatarPose, f32>,
    pub y: __sdk::__query_builder::Col<AvatarPose, f32>,
    pub updated_at: __sdk::__query_builder::Col<AvatarPose, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AvatarPose {
    type Cols = AvatarPoseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AvatarPoseCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AvatarPose`.
///
/// Provides typed access to indexed columns for query building.
pub struct AvatarPoseIxCols {
    pub owner: __sdk::__query_builder::IxCol<AvatarPose, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AvatarPose {
    type IxCols = AvatarPoseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AvatarPoseIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AvatarPose {}
