// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CaptureEvent {
    pub event_id: u64,
    pub recipient_key: String,
    pub catcher_name: String,
    pub species: String,
    pub instance_id: u64,
    pub created_micros: i64,
}

impl __sdk::InModule for CaptureEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CaptureEvent`.
///
/// Provides typed access to columns for query building.
pub struct CaptureEventCols {
    pub event_id: __sdk::__query_builder::Col<CaptureEvent, u64>,
    pub recipient_key: __sdk::__query_builder::Col<CaptureEvent, String>,
    pub catcher_name: __sdk::__query_builder::Col<CaptureEvent, String>,
    pub species: __sdk::__query_builder::Col<CaptureEvent, String>,
    pub instance_id: __sdk::__query_builder::Col<CaptureEvent, u64>,
    pub created_micros: __sdk::__query_builder::Col<CaptureEvent, i64>,
}

impl __sdk::__query_builder::HasCols for CaptureEvent {
    type Cols = CaptureEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CaptureEventCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            recipient_key: __sdk::__query_builder::Col::new(table_name, "recipient_key"),
            catcher_name: __sdk::__query_builder::Col::new(table_name, "catcher_name"),
            species: __sdk::__query_builder::Col::new(table_name, "species"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            created_micros: __sdk::__query_builder::Col::new(table_name, "created_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `CaptureEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CaptureEventIxCols {
    pub event_id: __sdk::__query_builder::IxCol<CaptureEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for CaptureEvent {
    type IxCols = CaptureEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CaptureEventIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CaptureEvent {}
