// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::capture_event_type::CaptureEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `capture_event`.
///
/// Obtain a handle from the [`CaptureEventTableAccess::capture_event`] method on [`super::RemoteTables`],
/// like `ctx.db.capture_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.capture_event().on_insert(...)`.
pub struct CaptureEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<CaptureEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `capture_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CaptureEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CaptureEventTableHandle`], which mediates access to the table `capture_event`.
    fn capture_event(&self) -> CaptureEventTableHandle<'_>;
}

impl CaptureEventTableAccess for super::RemoteTables {
    fn capture_event(&self) -> CaptureEventTableHandle<'_> {
        CaptureEventTableHandle {
            imp: self.imp.get_table::<CaptureEvent>("capture_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CaptureEventInsertCallbackId(__sdk::CallbackId);
pub struct CaptureEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CaptureEventTableHandle<'ctx> {
    type Row = CaptureEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CaptureEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CaptureEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CaptureEventInsertCallbackId {
        CaptureEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CaptureEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CaptureEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CaptureEventDeleteCallbackId {
        CaptureEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CaptureEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CaptureEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CaptureEventTableHandle<'ctx> {
    type UpdateCallbackId = CaptureEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CaptureEventUpdateCallbackId {
        CaptureEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CaptureEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `capture_event`,
/// which allows point queries on the field of the same name
/// via the [`CaptureEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.capture_event().event_id().find(...)`.
pub struct CaptureEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CaptureEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CaptureEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `capture_event`.
    pub fn event_id(&self) -> CaptureEventEventIdUnique<'ctx> {
        CaptureEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CaptureEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CaptureEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CaptureEvent>("capture_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CaptureEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CaptureEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CaptureEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait capture_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CaptureEvent`.
    fn capture_event(&self) -> __sdk::__query_builder::Table<CaptureEvent>;
}

impl capture_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn capture_event(&self) -> __sdk::__query_builder::Table<CaptureEvent> {
        __sdk::__query_builder::Table::new("capture_event")
    }
}
