// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EngageAnimalArgs {
    pub animal_uuid: String,
}

impl From<EngageAnimalArgs> for super::Reducer {
    fn from(args: EngageAnimalArgs) -> Self {
        Self::EngageAnimal {
            animal_uuid: args.animal_uuid,
        }
    }
}

impl __sdk::InModule for EngageAnimalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `engage_animal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait engage_animal {
    /// Request that the remote module invoke the reducer `engage_animal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`engage_animal:engage_animal_then`] to run a callback after the reducer completes.
    fn engage_animal(&self, animal_uuid: String) -> __sdk::Result<()> {
        self.engage_animal_then(animal_uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `engage_animal` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn engage_animal_then(
        &self,
        animal_uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl engage_animal for super::RemoteReducers {
    fn engage_animal_then(
        &self,
        animal_uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EngageAnimalArgs { animal_uuid }, callback)
    }
}
