// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::instance_member_type::InstanceMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `instance_member`.
///
/// Obtain a handle from the [`InstanceMemberTableAccess::instance_member`] method on [`super::RemoteTables`],
/// like `ctx.db.instance_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_member().on_insert(...)`.
pub struct InstanceMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<InstanceMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `instance_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InstanceMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InstanceMemberTableHandle`], which mediates access to the table `instance_member`.
    fn instance_member(&self) -> InstanceMemberTableHandle<'_>;
}

impl InstanceMemberTableAccess for super::RemoteTables {
    fn instance_member(&self) -> InstanceMemberTableHandle<'_> {
        InstanceMemberTableHandle {
            imp: self.imp.get_table::<InstanceMember>("instance_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InstanceMemberInsertCallbackId(__sdk::CallbackId);
pub struct InstanceMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InstanceMemberTableHandle<'ctx> {
    type Row = InstanceMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InstanceMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InstanceMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceMemberInsertCallbackId {
        InstanceMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InstanceMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InstanceMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceMemberDeleteCallbackId {
        InstanceMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InstanceMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InstanceMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InstanceMemberTableHandle<'ctx> {
    type UpdateCallbackId = InstanceMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InstanceMemberUpdateCallbackId {
        InstanceMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InstanceMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `member_key` unique index on the table `instance_member`,
/// which allows point queries on the field of the same name
/// via the [`InstanceMemberMemberKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_member().member_key().find(...)`.
pub struct InstanceMemberMemberKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InstanceMember, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InstanceMemberTableHandle<'ctx> {
    /// Get a handle on the `member_key` unique index on the table `instance_member`.
    pub fn member_key(&self) -> InstanceMemberMemberKeyUnique<'ctx> {
        InstanceMemberMemberKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("member_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InstanceMemberMemberKeyUnique<'ctx> {
    /// Find the subscribed row whose `member_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<InstanceMember> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InstanceMember>("instance_member");
    _table.add_unique_constraint::<String>("member_key", |row| &row.member_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InstanceMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InstanceMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InstanceMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait instance_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InstanceMember`.
    fn instance_member(&self) -> __sdk::__query_builder::Table<InstanceMember>;
}

impl instance_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn instance_member(&self) -> __sdk::__query_builder::Table<InstanceMember> {
        __sdk::__query_builder::Table::new("instance_member")
    }
}
