// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InstanceMember {
    pub member_key: String,
    pub instance_id: u64,
}

impl __sdk::InModule for InstanceMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InstanceMember`.
///
/// Provides typed access to columns for query building.
pub struct InstanceMemberCols {
    pub member_key: __sdk::__query_builder::Col<InstanceMember, String>,
    pub instance_id: __sdk::__query_builder::Col<InstanceMember, u64>,
}

impl __sdk::__query_builder::HasCols for InstanceMember {
    type Cols = InstanceMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceMemberCols {
            member_key: __sdk::__query_builder::Col::new(table_name, "member_key"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}

/// Indexed column accessor struct for the table `InstanceMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceMemberIxCols {
    pub member_key: __sdk::__query_builder::IxCol<InstanceMember, String>,
}

impl __sdk::__query_builder::HasIxCols for InstanceMember {
    type IxCols = InstanceMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceMemberIxCols {
            member_key: __sdk::__query_builder::IxCol::new(table_name, "member_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InstanceMember {}
