// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::instance_engagement_type::InstanceEngagement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `instance_engagement`.
///
/// Obtain a handle from the [`InstanceEngagementTableAccess::instance_engagement`] method on [`super::RemoteTables`],
/// like `ctx.db.instance_engagement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_engagement().on_insert(...)`.
pub struct InstanceEngagementTableHandle<'ctx> {
    imp: __sdk::TableHandle<InstanceEngagement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `instance_engagement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InstanceEngagementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InstanceEngagementTableHandle`], which mediates access to the table `instance_engagement`.
    fn instance_engagement(&self) -> InstanceEngagementTableHandle<'_>;
}

impl InstanceEngagementTableAccess for super::RemoteTables {
    fn instance_engagement(&self) -> InstanceEngagementTableHandle<'_> {
        InstanceEngagementTableHandle {
            imp: self
                .imp
                .get_table::<InstanceEngagement>("instance_engagement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InstanceEngagementInsertCallbackId(__sdk::CallbackId);
pub struct InstanceEngagementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InstanceEngagementTableHandle<'ctx> {
    type Row = InstanceEngagement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InstanceEngagement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InstanceEngagementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceEngagementInsertCallbackId {
        InstanceEngagementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InstanceEngagementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InstanceEngagementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InstanceEngagementDeleteCallbackId {
        InstanceEngagementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InstanceEngagementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InstanceEngagementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InstanceEngagementTableHandle<'ctx> {
    type UpdateCallbackId = InstanceEngagementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InstanceEngagementUpdateCallbackId {
        InstanceEngagementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InstanceEngagementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `engage_key` unique index on the table `instance_engagement`,
/// which allows point queries on the field of the same name
/// via the [`InstanceEngagementEngageKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.instance_engagement().engage_key().find(...)`.
pub struct InstanceEngagementEngageKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InstanceEngagement, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InstanceEngagementTableHandle<'ctx> {
    /// Get a handle on the `engage_key` unique index on the table `instance_engagement`.
    pub fn engage_key(&self) -> InstanceEngagementEngageKeyUnique<'ctx> {
        InstanceEngagementEngageKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("engage_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InstanceEngagementEngageKeyUnique<'ctx> {
    /// Find the subscribed row whose `engage_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<InstanceEngagement> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InstanceEngagement>("instance_engagement");
    _table.add_unique_constraint::<String>("engage_key", |row| &row.engage_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InstanceEngagement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InstanceEngagement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InstanceEngagement`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait instance_engagementQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InstanceEngagement`.
    fn instance_engagement(&self) -> __sdk::__query_builder::Table<InstanceEngagement>;
}

impl instance_engagementQueryTableAccess for __sdk::QueryTableAccessor {
    fn instance_engagement(&self) -> __sdk::__query_builder::Table<InstanceEngagement> {
        __sdk::__query_builder::Table::new("instance_engagement")
    }
}
