// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InstanceEngagement {
    pub engage_key: String,
    pub animal_uuid: String,
    pub member_key: String,
    pub instance_id: u64,
}

impl __sdk::InModule for InstanceEngagement {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InstanceEngagement`.
///
/// Provides typed access to columns for query building.
pub struct InstanceEngagementCols {
    pub engage_key: __sdk::__query_builder::Col<InstanceEngagement, String>,
    pub animal_uuid: __sdk::__query_builder::Col<InstanceEngagement, String>,
    pub member_key: __sdk::__query_builder::Col<InstanceEngagement, String>,
    pub instance_id: __sdk::__query_builder::Col<InstanceEngagement, u64>,
}

impl __sdk::__query_builder::HasCols for InstanceEngagement {
    type Cols = InstanceEngagementCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceEngagementCols {
            engage_key: __sdk::__query_builder::Col::new(table_name, "engage_key"),
            animal_uuid: __sdk::__query_builder::Col::new(table_name, "animal_uuid"),
            member_key: __sdk::__query_builder::Col::new(table_name, "member_key"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}

/// Indexed column accessor struct for the table `InstanceEngagement`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceEngagementIxCols {
    pub engage_key: __sdk::__query_builder::IxCol<InstanceEngagement, String>,
}

impl __sdk::__query_builder::HasIxCols for InstanceEngagement {
    type IxCols = InstanceEngagementIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceEngagementIxCols {
            engage_key: __sdk::__query_builder::IxCol::new(table_name, "engage_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InstanceEngagement {}
