// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InstanceAnimal {
    pub animal_uuid: String,
    pub instance_id: u64,
    pub species: String,
    pub x: f32,
    pub y: f32,
}

impl __sdk::InModule for InstanceAnimal {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InstanceAnimal`.
///
/// Provides typed access to columns for query building.
pub struct InstanceAnimalCols {
    pub animal_uuid: __sdk::__query_builder::Col<InstanceAnimal, String>,
    pub instance_id: __sdk::__query_builder::Col<InstanceAnimal, u64>,
    pub species: __sdk::__query_builder::Col<InstanceAnimal, String>,
    pub x: __sdk::__query_builder::Col<InstanceAnimal, f32>,
    pub y: __sdk::__query_builder::Col<InstanceAnimal, f32>,
}

impl __sdk::__query_builder::HasCols for InstanceAnimal {
    type Cols = InstanceAnimalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceAnimalCols {
            animal_uuid: __sdk::__query_builder::Col::new(table_name, "animal_uuid"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            species: __sdk::__query_builder::Col::new(table_name, "species"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
        }
    }
}

/// Indexed column accessor struct for the table `InstanceAnimal`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceAnimalIxCols {
    pub animal_uuid: __sdk::__query_builder::IxCol<InstanceAnimal, String>,
}

impl __sdk::__query_builder::HasIxCols for InstanceAnimal {
    type IxCols = InstanceAnimalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceAnimalIxCols {
            animal_uuid: __sdk::__query_builder::IxCol::new(table_name, "animal_uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InstanceAnimal {}
