// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Instance {
    pub instance_id: u64,
    pub scope_key: String,
    pub theme: String,
    pub seed: u64,
    pub created_at: __sdk::Timestamp,
    pub empty_since_micros: i64,
}

impl __sdk::InModule for Instance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Instance`.
///
/// Provides typed access to columns for query building.
pub struct InstanceCols {
    pub instance_id: __sdk::__query_builder::Col<Instance, u64>,
    pub scope_key: __sdk::__query_builder::Col<Instance, String>,
    pub theme: __sdk::__query_builder::Col<Instance, String>,
    pub seed: __sdk::__query_builder::Col<Instance, u64>,
    pub created_at: __sdk::__query_builder::Col<Instance, __sdk::Timestamp>,
    pub empty_since_micros: __sdk::__query_builder::Col<Instance, i64>,
}

impl __sdk::__query_builder::HasCols for Instance {
    type Cols = InstanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InstanceCols {
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            scope_key: __sdk::__query_builder::Col::new(table_name, "scope_key"),
            theme: __sdk::__query_builder::Col::new(table_name, "theme"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            empty_since_micros: __sdk::__query_builder::Col::new(table_name, "empty_since_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Instance`.
///
/// Provides typed access to indexed columns for query building.
pub struct InstanceIxCols {
    pub instance_id: __sdk::__query_builder::IxCol<Instance, u64>,
}

impl __sdk::__query_builder::HasIxCols for Instance {
    type IxCols = InstanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InstanceIxCols {
            instance_id: __sdk::__query_builder::IxCol::new(table_name, "instance_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Instance {}
