// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveAvatarArgs {
    pub x: f32,
    pub y: f32,
}

impl From<MoveAvatarArgs> for super::Reducer {
    fn from(args: MoveAvatarArgs) -> Self {
        Self::MoveAvatar {
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for MoveAvatarArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_avatar`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_avatar {
    /// Request that the remote module invoke the reducer `move_avatar` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_avatar:move_avatar_then`] to run a callback after the reducer completes.
    fn move_avatar(&self, x: f32, y: f32) -> __sdk::Result<()> {
        self.move_avatar_then(x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_avatar` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_avatar_then(
        &self,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_avatar for super::RemoteReducers {
    fn move_avatar_then(
        &self,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveAvatarArgs { x, y }, callback)
    }
}
