// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyInvite {
    pub invite_id: u64,
    pub party_id: u64,
    pub from_key: String,
    pub to_key: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for PartyInvite {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyInvite`.
///
/// Provides typed access to columns for query building.
pub struct PartyInviteCols {
    pub invite_id: __sdk::__query_builder::Col<PartyInvite, u64>,
    pub party_id: __sdk::__query_builder::Col<PartyInvite, u64>,
    pub from_key: __sdk::__query_builder::Col<PartyInvite, String>,
    pub to_key: __sdk::__query_builder::Col<PartyInvite, String>,
    pub created_at: __sdk::__query_builder::Col<PartyInvite, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PartyInvite {
    type Cols = PartyInviteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyInviteCols {
            invite_id: __sdk::__query_builder::Col::new(table_name, "invite_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            from_key: __sdk::__query_builder::Col::new(table_name, "from_key"),
            to_key: __sdk::__query_builder::Col::new(table_name, "to_key"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyInvite`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyInviteIxCols {
    pub invite_id: __sdk::__query_builder::IxCol<PartyInvite, u64>,
}

impl __sdk::__query_builder::HasIxCols for PartyInvite {
    type IxCols = PartyInviteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyInviteIxCols {
            invite_id: __sdk::__query_builder::IxCol::new(table_name, "invite_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyInvite {}
