// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ZooRow {
    pub owner: __sdk::Identity,
    pub slot: u64,
    pub plot_x: f32,
    pub plot_y: f32,
    pub coins: u64,
    pub snapshot_json: String,
}

impl __sdk::InModule for ZooRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ZooRow`.
///
/// Provides typed access to columns for query building.
pub struct ZooRowCols {
    pub owner: __sdk::__query_builder::Col<ZooRow, __sdk::Identity>,
    pub slot: __sdk::__query_builder::Col<ZooRow, u64>,
    pub plot_x: __sdk::__query_builder::Col<ZooRow, f32>,
    pub plot_y: __sdk::__query_builder::Col<ZooRow, f32>,
    pub coins: __sdk::__query_builder::Col<ZooRow, u64>,
    pub snapshot_json: __sdk::__query_builder::Col<ZooRow, String>,
}

impl __sdk::__query_builder::HasCols for ZooRow {
    type Cols = ZooRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ZooRowCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            plot_x: __sdk::__query_builder::Col::new(table_name, "plot_x"),
            plot_y: __sdk::__query_builder::Col::new(table_name, "plot_y"),
            coins: __sdk::__query_builder::Col::new(table_name, "coins"),
            snapshot_json: __sdk::__query_builder::Col::new(table_name, "snapshot_json"),
        }
    }
}

/// Indexed column accessor struct for the table `ZooRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ZooRowIxCols {
    pub owner: __sdk::__query_builder::IxCol<ZooRow, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ZooRow {
    type IxCols = ZooRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ZooRowIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ZooRow {}
