// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::zoo_row_type::ZooRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `zoo`.
///
/// Obtain a handle from the [`ZooTableAccess::zoo`] method on [`super::RemoteTables`],
/// like `ctx.db.zoo()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zoo().on_insert(...)`.
pub struct ZooTableHandle<'ctx> {
    imp: __sdk::TableHandle<ZooRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `zoo`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ZooTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ZooTableHandle`], which mediates access to the table `zoo`.
    fn zoo(&self) -> ZooTableHandle<'_>;
}

impl ZooTableAccess for super::RemoteTables {
    fn zoo(&self) -> ZooTableHandle<'_> {
        ZooTableHandle {
            imp: self.imp.get_table::<ZooRow>("zoo"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ZooInsertCallbackId(__sdk::CallbackId);
pub struct ZooDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ZooTableHandle<'ctx> {
    type Row = ZooRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ZooRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ZooInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZooInsertCallbackId {
        ZooInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ZooInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ZooDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZooDeleteCallbackId {
        ZooDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ZooDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ZooUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ZooTableHandle<'ctx> {
    type UpdateCallbackId = ZooUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ZooUpdateCallbackId {
        ZooUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ZooUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `owner_key` unique index on the table `zoo`,
/// which allows point queries on the field of the same name
/// via the [`ZooOwnerKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zoo().owner_key().find(...)`.
pub struct ZooOwnerKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ZooRow, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ZooTableHandle<'ctx> {
    /// Get a handle on the `owner_key` unique index on the table `zoo`.
    pub fn owner_key(&self) -> ZooOwnerKeyUnique<'ctx> {
        ZooOwnerKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("owner_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ZooOwnerKeyUnique<'ctx> {
    /// Find the subscribed row whose `owner_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ZooRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ZooRow>("zoo");
    _table.add_unique_constraint::<String>("owner_key", |row| &row.owner_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ZooRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ZooRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ZooRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait zooQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ZooRow`.
    fn zoo(&self) -> __sdk::__query_builder::Table<ZooRow>;
}

impl zooQueryTableAccess for __sdk::QueryTableAccessor {
    fn zoo(&self) -> __sdk::__query_builder::Table<ZooRow> {
        __sdk::__query_builder::Table::new("zoo")
    }
}
