//! Embed Windows resources (icon + version metadata) into the final exe.
//!
//! No-op on non-Windows targets. If `assets/icon.ico` doesn't exist yet,
//! the build still succeeds but the exe falls back to the default Windows
//! application icon and a `cargo:warning` is emitted so it's obvious.

fn main() {
    // The `cfg(windows)` build-dependency gate in Cargo.toml makes
    // `winresource` only available on Windows targets, but the build script
    // itself runs on every target — so cfg-out the body explicitly too.
    #[cfg(windows)]
    embed_windows_resources();
    // When the Steam transport is compiled in, drop its runtime files next to
    // the produced exe so a distributed (double-clicked) build runs standalone.
    #[cfg(windows)]
    place_steam_runtime();
    // Each call scans one assets subdir of PNGs into a generated `(&str, &[u8])`
    // table the lib `include!`s. New art is picked up by dropping a PNG and
    // rebuilding — no code edits.
    emit_png_table("assets/animals", "animal_icons_table.rs");
    emit_png_table("assets/tiles", "tile_table.rs");
    emit_png_table("assets/habitats", "habitat_table.rs");
    emit_png_table("assets/icons", "icon_table.rs");
    emit_png_table("assets/npcs", "npc_table.rs");
    emit_png_table("assets/hotbar", "hotbar_table.rs");
    emit_png_table("assets/ui", "ui_table.rs");
    emit_png_table("assets/structures", "structure_table.rs");
    emit_png_table("assets/player", "player_table.rs");
    emit_png_table("assets/skills", "skill_table.rs");
    // Terrain props live in per-biome subfolders (`assets/terrain/<Biome>/*.png`);
    // each entry is keyed `"<biome>/<stem>"` so the renderer can pick scenery by
    // biome. Subfolder names should match the biome display names (case-insensitive).
    emit_nested_png_table("assets/terrain", "terrain_table.rs");
    emit_asset_table("assets/sfx", "sfx_table.rs", &["ogg", "wav"]);
    emit_asset_table("assets/fonts", "font_table.rs", &["ttf", "otf"]);
}

/// Scan `<dir>/<sub>/*.png` (one level of subfolders) into a `(&str, &[u8])`
/// table keyed `"<sub>/<stem>"`. Used for terrain props grouped by biome. The
/// top dir (and each subfolder) may be absent — an empty table is emitted so the
/// `include!` still compiles.
fn emit_nested_png_table(dir: &str, dest_name: &str) {
    use std::fs;
    use std::io::Write;
    use std::path::PathBuf;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = PathBuf::from(&out_dir).join(dest_name);
    let root = PathBuf::from(dir);

    println!("cargo:rerun-if-changed={dir}");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if root.exists() {
        for sub in fs::read_dir(&root).unwrap_or_else(|_| panic!("read {dir}")).flatten() {
            let sub_path = sub.path();
            if !sub_path.is_dir() {
                continue;
            }
            let sub_name = match sub_path.file_name().and_then(|x| x.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            // Watch nested files too (a dir watch alone misses inner edits).
            println!("cargo:rerun-if-changed={}", sub_path.display());
            for e in fs::read_dir(&sub_path).unwrap_or_else(|_| panic!("read {sub_name}")).flatten() {
                let path = e.path();
                let is_png = path
                    .extension()
                    .and_then(|x| x.to_str())
                    .map(|x| x.eq_ignore_ascii_case("png"))
                    .unwrap_or(false);
                if !is_png {
                    continue;
                }
                let stem = match path.file_stem().and_then(|x| x.to_str()) {
                    Some(s) => s.to_string(),
                    None => continue,
                };
                let key = format!("{sub_name}/{stem}");
                let abs = path.canonicalize().unwrap_or(path.clone());
                entries.push((key, abs));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = fs::File::create(&dest).unwrap_or_else(|_| panic!("create {dest_name}"));
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "&[").unwrap();
    for (key, abs) in &entries {
        writeln!(out, "    (\"{}\", include_bytes!(r\"{}\")),", key, abs.display()).unwrap();
    }
    writeln!(out, "]").unwrap();
}

/// Scan `<dir>/*.png` into a `(&str, &[u8])` table. Thin wrapper over
/// `emit_asset_table` for the common PNG case.
fn emit_png_table(dir: &str, dest_name: &str) {
    emit_asset_table(dir, dest_name, &["png"]);
}

/// Scan `<dir>` for files with any of `exts` and write a static
/// `(&str, &[u8])` slice into `$OUT_DIR/<dest_name>` that the lib `include!`s.
/// The directory may not exist yet (e.g. `assets/sfx` before sounds land) — in
/// that case an empty table is emitted so the `include!` still compiles.
fn emit_asset_table(dir: &str, dest_name: &str, exts: &[&str]) {
    use std::fs;
    use std::io::Write;
    use std::path::PathBuf;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = PathBuf::from(&out_dir).join(dest_name);
    let assets_dir = PathBuf::from(dir);

    // Re-run this script whenever a file is added/removed/edited in the dir.
    println!("cargo:rerun-if-changed={dir}");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if assets_dir.exists() {
        for e in fs::read_dir(&assets_dir)
            .unwrap_or_else(|_| panic!("read {dir}"))
            .flatten()
        {
            let path = e.path();
            let ext_ok = path
                .extension()
                .and_then(|x| x.to_str())
                .map(|x| exts.contains(&x))
                .unwrap_or(false);
            if !ext_ok {
                continue;
            }
            let stem = match path.file_stem().and_then(|x| x.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            let abs = path.canonicalize().unwrap_or(path.clone());
            entries.push((stem, abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = fs::File::create(&dest).unwrap_or_else(|_| panic!("create {dest_name}"));
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "&[").unwrap();
    for (stem, abs) in &entries {
        // Use raw string literals so Windows backslashes don't need escaping.
        writeln!(
            out,
            "    (\"{}\", include_bytes!(r\"{}\")),",
            stem,
            abs.display()
        )
        .unwrap();
    }
    writeln!(out, "]").unwrap();
}

#[cfg(windows)]
fn embed_windows_resources() {
    use std::path::Path;

    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=build.rs");

    let mut res = winresource::WindowsResource::new();
    // The package-level fields in Cargo.toml (`name`, `version`,
    // `description`) flow in automatically via the CARGO_PKG_* env vars
    // that Cargo sets for build scripts. We only override what we want
    // explicit in Explorer's "Details" tab.
    res.set("FileDescription", "cmd_zoo")
        .set("ProductName", "cmd_zoo");

    let icon = Path::new("assets/icon.ico");
    if icon.exists() {
        res.set_icon(icon.to_str().expect("icon path is non-utf8"));
    } else {
        println!(
            "cargo:warning=assets/icon.ico not found — using Windows' default exe icon. \
             Drop a 256x256 .ico in assets/ and rebuild to embed one."
        );
    }

    if let Err(e) = res.compile() {
        // Don't hard-fail the build on a resource error — emit a warning so
        // `cargo run` still works during development on non-MSVC toolchains.
        println!("cargo:warning=failed to embed Windows resources: {e}");
    }
}

/// Copy the Steam runtime files (`steam_api64.dll` + `steam_appid.txt`) next to
/// the produced executable when building with the `steam` feature.
///
/// `steamworks-sys` only copies the DLL into its own private build dir
/// (`target/<profile>/build/steamworks-sys-*/out/`), which Cargo adds to the
/// DLL search PATH during `cargo run` — but a standalone, double-clicked
/// release exe gets no such help and Windows only searches beside the exe. So
/// we mirror both files into the profile output dir to make distribution builds
/// self-contained. Best-effort: warnings only, never fails the build.
#[cfg(windows)]
fn place_steam_runtime() {
    use std::path::PathBuf;

    // Cargo sets `CARGO_FEATURE_<NAME>` for each enabled feature.
    if std::env::var_os("CARGO_FEATURE_STEAM").is_none() {
        return;
    }
    println!("cargo:rerun-if-changed=steam_appid.txt");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    // OUT_DIR = <target>/<profile>/build/<our-pkg>-<hash>/out
    //   → the profile dir (where the exe lands) is three levels up.
    let Some(profile_dir) = out_dir.ancestors().nth(3).map(PathBuf::from) else {
        println!("cargo:warning=steam: could not resolve the target profile dir; \
                  copy steam_api64.dll next to the exe manually");
        return;
    };

    // Source DLL: prefer an explicit SDK location, else the sibling
    // steamworks-sys build dir that already holds the copied redistributable.
    let build_dir = profile_dir.join("build");
    let dll_src = steam_sdk_dll().or_else(|| {
        std::fs::read_dir(&build_dir).ok().and_then(|entries| {
            entries.flatten().find_map(|e| {
                e.file_name()
                    .to_string_lossy()
                    .starts_with("steamworks-sys-")
                    .then(|| e.path().join("out").join("steam_api64.dll"))
                    .filter(|p| p.exists())
            })
        })
    });

    match dll_src {
        Some(src) => {
            let dst = profile_dir.join("steam_api64.dll");
            if let Err(e) = std::fs::copy(&src, &dst) {
                println!("cargo:warning=steam: failed to copy steam_api64.dll to {}: {e}",
                    dst.display());
            }
        }
        None => println!(
            "cargo:warning=steam: steam_api64.dll not found (looked in {} and \
             $STEAM_SDK_LOCATION); copy it next to the exe manually",
            build_dir.display()
        ),
    }

    // Mirror steam_appid.txt so a packaged build finds its app id beside the exe.
    let appid = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("steam_appid.txt");
    if appid.exists() {
        let _ = std::fs::copy(&appid, profile_dir.join("steam_appid.txt"));
    }
}

/// `steam_api64.dll` under `$STEAM_SDK_LOCATION`, if that env var points at a
/// Steamworks SDK. Mirrors how `steamworks-sys` resolves the SDK.
#[cfg(windows)]
fn steam_sdk_dll() -> Option<std::path::PathBuf> {
    let sdk = std::env::var_os("STEAM_SDK_LOCATION")?;
    let dll = std::path::PathBuf::from(sdk)
        .join("redistributable_bin")
        .join("win64")
        .join("steam_api64.dll");
    dll.exists().then_some(dll)
}
