//! Embed Windows resources (icon + version metadata) into the final exe.
//!
//! No-op on non-Windows targets. If `assets/icon.ico` doesn't exist yet,
//! the build still succeeds but the exe falls back to the default Windows
//! application icon and a `cargo:warning` is emitted so it's obvious.

fn main() {
    // The `cfg(windows)` build-dependency gate in Cargo.toml makes
    // `winresource` only available on Windows targets, but the build script
    // itself runs on every target — so cfg-out the body explicitly too.
    #[cfg(windows)]
    embed_windows_resources();
    emit_animal_icon_table();
}

/// Scan `assets/animals/*.png` and write a static `(&str, &[u8])` slice into
/// `$OUT_DIR/animal_icons_table.rs` that the lib `include!`s. New PNGs are
/// picked up by adding the file and re-running `cargo build` — no code edits.
fn emit_animal_icon_table() {
    use std::fs;
    use std::io::Write;
    use std::path::PathBuf;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = PathBuf::from(&out_dir).join("animal_icons_table.rs");
    let assets_dir = PathBuf::from("assets/animals");

    // Tell cargo to re-run this script whenever a PNG is added/removed/edited.
    println!("cargo:rerun-if-changed=assets/animals");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if assets_dir.exists() {
        for e in fs::read_dir(&assets_dir).expect("read assets/animals").flatten() {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) != Some("png") {
                continue;
            }
            let stem = match path.file_stem().and_then(|x| x.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            let abs = path.canonicalize().unwrap_or(path.clone());
            entries.push((stem, abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = fs::File::create(&dest).expect("create animal_icons_table.rs");
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "&[").unwrap();
    for (stem, abs) in &entries {
        // Use raw string literals so Windows backslashes don't need escaping.
        writeln!(
            out,
            "    (\"{}\", include_bytes!(r\"{}\")),",
            stem,
            abs.display()
        )
        .unwrap();
    }
    writeln!(out, "]").unwrap();
}

#[cfg(windows)]
fn embed_windows_resources() {
    use std::path::Path;

    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=build.rs");

    let mut res = winresource::WindowsResource::new();
    // The package-level fields in Cargo.toml (`name`, `version`,
    // `description`) flow in automatically via the CARGO_PKG_* env vars
    // that Cargo sets for build scripts. We only override what we want
    // explicit in Explorer's "Details" tab.
    res.set("FileDescription", "cmd_zoo")
        .set("ProductName", "cmd_zoo");

    let icon = Path::new("assets/icon.ico");
    if icon.exists() {
        res.set_icon(icon.to_str().expect("icon path is non-utf8"));
    } else {
        println!(
            "cargo:warning=assets/icon.ico not found — using Windows' default exe icon. \
             Drop a 256x256 .ico in assets/ and rebuild to embed one."
        );
    }

    if let Err(e) = res.compile() {
        // Don't hard-fail the build on a resource error — emit a warning so
        // `cargo run` still works during development on non-MSVC toolchains.
        println!("cargo:warning=failed to embed Windows resources: {e}");
    }
}
