//! Embed Windows resources (icon + version metadata) into the final exe.
//!
//! No-op on non-Windows targets. If `assets/icon.ico` doesn't exist yet,
//! the build still succeeds but the exe falls back to the default Windows
//! application icon and a `cargo:warning` is emitted so it's obvious.

fn main() {
    // The `cfg(windows)` build-dependency gate in Cargo.toml makes
    // `winresource` only available on Windows targets, but the build script
    // itself runs on every target — so cfg-out the body explicitly too.
    #[cfg(windows)]
    embed_windows_resources();
    // Each call scans one assets subdir of PNGs into a generated `(&str, &[u8])`
    // table the lib `include!`s. New art is picked up by dropping a PNG and
    // rebuilding — no code edits.
    emit_png_table("assets/animals", "animal_icons_table.rs");
    emit_png_table("assets/tiles", "tile_table.rs");
    emit_png_table("assets/habitats", "habitat_table.rs");
    emit_png_table("assets/icons", "icon_table.rs");
    emit_asset_table("assets/sfx", "sfx_table.rs", &["ogg", "wav"]);
}

/// Scan `<dir>/*.png` into a `(&str, &[u8])` table. Thin wrapper over
/// `emit_asset_table` for the common PNG case.
fn emit_png_table(dir: &str, dest_name: &str) {
    emit_asset_table(dir, dest_name, &["png"]);
}

/// Scan `<dir>` for files with any of `exts` and write a static
/// `(&str, &[u8])` slice into `$OUT_DIR/<dest_name>` that the lib `include!`s.
/// The directory may not exist yet (e.g. `assets/sfx` before sounds land) — in
/// that case an empty table is emitted so the `include!` still compiles.
fn emit_asset_table(dir: &str, dest_name: &str, exts: &[&str]) {
    use std::fs;
    use std::io::Write;
    use std::path::PathBuf;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = PathBuf::from(&out_dir).join(dest_name);
    let assets_dir = PathBuf::from(dir);

    // Re-run this script whenever a file is added/removed/edited in the dir.
    println!("cargo:rerun-if-changed={dir}");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if assets_dir.exists() {
        for e in fs::read_dir(&assets_dir)
            .unwrap_or_else(|_| panic!("read {dir}"))
            .flatten()
        {
            let path = e.path();
            let ext_ok = path
                .extension()
                .and_then(|x| x.to_str())
                .map(|x| exts.contains(&x))
                .unwrap_or(false);
            if !ext_ok {
                continue;
            }
            let stem = match path.file_stem().and_then(|x| x.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            let abs = path.canonicalize().unwrap_or(path.clone());
            entries.push((stem, abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = fs::File::create(&dest).unwrap_or_else(|_| panic!("create {dest_name}"));
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "&[").unwrap();
    for (stem, abs) in &entries {
        // Use raw string literals so Windows backslashes don't need escaping.
        writeln!(
            out,
            "    (\"{}\", include_bytes!(r\"{}\")),",
            stem,
            abs.display()
        )
        .unwrap();
    }
    writeln!(out, "]").unwrap();
}

#[cfg(windows)]
fn embed_windows_resources() {
    use std::path::Path;

    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=build.rs");

    let mut res = winresource::WindowsResource::new();
    // The package-level fields in Cargo.toml (`name`, `version`,
    // `description`) flow in automatically via the CARGO_PKG_* env vars
    // that Cargo sets for build scripts. We only override what we want
    // explicit in Explorer's "Details" tab.
    res.set("FileDescription", "cmd_zoo")
        .set("ProductName", "cmd_zoo");

    let icon = Path::new("assets/icon.ico");
    if icon.exists() {
        res.set_icon(icon.to_str().expect("icon path is non-utf8"));
    } else {
        println!(
            "cargo:warning=assets/icon.ico not found — using Windows' default exe icon. \
             Drop a 256x256 .ico in assets/ and rebuild to embed one."
        );
    }

    if let Err(e) = res.compile() {
        // Don't hard-fail the build on a resource error — emit a warning so
        // `cargo run` still works during development on non-MSVC toolchains.
        println!("cargo:warning=failed to embed Windows resources: {e}");
    }
}
